# This GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under travel_recommendations_model/assets/*
# and travel_recommendations_model/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for travel_recommendations_model Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./travel_recommendations_model

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: travel_recommendations_model-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.211.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
