# This GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under travel_recommendations_model/assets/*
# and travel_recommendations_model/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for travel_recommendations_model Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./travel_recommendations_model

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: travel_recommendations_model-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.211.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
